[package]
name = "ddavness/curve"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "LICENSE", "wally.toml"]

[dependencies]
